# Generated by Django 6.0.5 on 2026-05-09 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Número inválido. Usa formato internacional: +51999888777', regex='^\\+?1?\\d{7,15}$')], verbose_name='Teléfono')),
                ('relacion', models.CharField(choices=[('familiar', 'Familiar'), ('amigo', 'Amigo/a'), ('medico', 'Médico/a'), ('vecino', 'Vecino/a'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Relación')),
                ('es_principal', models.BooleanField(default=False, help_text='Contacto principal que se muestra primero en el botón SOS.', verbose_name='Es contacto principal')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Contacto de emergencia',
                'verbose_name_plural': 'Contactos de emergencia',
                'ordering': ['-es_principal', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EventoSOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activado', 'Activado'), ('resuelto', 'Resuelto'), ('falsa_alarma', 'Falsa Alarma')], db_index=True, default='activado', max_length=20, verbose_name='Estado')),
                ('ubicacion_latitud', models.DecimalField(blank=True, decimal_places=6, help_text='Latitud GPS del dispositivo al momento del SOS.', max_digits=9, null=True, verbose_name='Latitud')),
                ('ubicacion_longitud', models.DecimalField(blank=True, decimal_places=6, help_text='Longitud GPS del dispositivo al momento del SOS.', max_digits=9, null=True, verbose_name='Longitud')),
                ('notas', models.TextField(blank=True, default='', help_text='Observaciones del usuario al resolver o marcar como falsa alarma.', verbose_name='Notas')),
                ('activado_en', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático del momento de activación.', verbose_name='Activado el')),
                ('resuelto_en', models.DateTimeField(blank=True, help_text='Cuándo fue resuelto o marcado como falsa alarma.', null=True, verbose_name='Resuelto el')),
            ],
            options={
                'verbose_name': 'Evento SOS',
                'verbose_name_plural': 'Eventos SOS',
                'ordering': ['-activado_en'],
            },
        ),
        migrations.CreateModel(
            name='NumeroServicioEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del servicio')),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Número inválido. Usa formato internacional: +51999888777', regex='^\\+?1?\\d{7,15}$')], verbose_name='Teléfono')),
                ('tipo_servicio', models.CharField(choices=[('policia', 'Policía'), ('ambulancia', 'Ambulancia'), ('bomberos', 'Bomberos'), ('general', 'Emergencias General'), ('otro', 'Otro')], default='general', max_length=20, verbose_name='Tipo de servicio')),
                ('codigo_pais', models.CharField(db_index=True, default='PE', help_text='Código ISO del país: PE, CO, MX, etc.', max_length=5, verbose_name='Código de país')),
                ('descripcion', models.CharField(blank=True, default='', max_length=255, verbose_name='Descripción')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('prioridad', models.PositiveSmallIntegerField(default=100, help_text='Menor número = mayor prioridad en la lista. El 112 debería tener prioridad=1.', verbose_name='Prioridad')),
            ],
            options={
                'verbose_name': 'Número de servicio de emergencia',
                'verbose_name_plural': 'Números de servicios de emergencia',
                'ordering': ['prioridad', 'nombre'],
            },
        ),
    ]
