# Generated by Django 6.0.5 on 2026-05-16 20:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroServicioEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del servicio')),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Número inválido. Usa formato internacional: +51999888777', regex='^\\+?1?\\d{7,15}$')], verbose_name='Teléfono')),
                ('tipo_servicio', models.CharField(choices=[('policia', 'Policía'), ('ambulancia', 'Ambulancia'), ('bomberos', 'Bomberos'), ('general', 'Emergencias General'), ('otro', 'Otro')], default='general', max_length=20, verbose_name='Tipo de servicio')),
                ('codigo_pais', models.CharField(db_index=True, default='PE', help_text='Código ISO del país: PE, CO, MX, etc.', max_length=5, verbose_name='Código de país')),
                ('descripcion', models.CharField(blank=True, default='', max_length=255, verbose_name='Descripción')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('prioridad', models.PositiveSmallIntegerField(default=100, help_text='Menor número = mayor prioridad en la lista. El 112 debería tener prioridad=1.', verbose_name='Prioridad')),
                ('icono', models.CharField(blank=True, default='', help_text='Nombre del ícono a mostrar en el frontend. Ej: "ambulance", "police", "fire".', max_length=50, verbose_name='Ícono')),
                ('url_sitio_web', models.URLField(blank=True, help_text='URL del sitio oficial del servicio. Ej: https://www.pnp.gob.pe/', null=True, verbose_name='Sitio web')),
                ('horario_atencion', models.CharField(blank=True, default='24/7', help_text='Descripción del horario. Ej: "24/7", "Lun-Vie 08:00-18:00".', max_length=100, verbose_name='Horario de atención')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Número de servicio de emergencia',
                'verbose_name_plural': 'Números de servicios de emergencia',
                'ordering': ['prioridad', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('telefono', 'codigo_pais'), name='telefono_unico_por_pais')],
            },
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Número inválido. Usa formato internacional: +51999888777', regex='^\\+?1?\\d{7,15}$')], verbose_name='Teléfono')),
                ('relacion', models.CharField(choices=[('familiar', 'Familiar'), ('amigo', 'Amigo/a'), ('medico', 'Médico/a'), ('vecino', 'Vecino/a'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Relación')),
                ('es_principal', models.BooleanField(default=False, help_text='Contacto principal que se muestra primero en el botón SOS.', verbose_name='Es contacto principal')),
                ('email', models.EmailField(blank=True, help_text='Email del contacto para notificaciones opcionales.', max_length=254, null=True, verbose_name='Correo electrónico')),
                ('notas', models.CharField(blank=True, default='', help_text='Información adicional del contacto. Ej: "Disponible solo en horario laboral".', max_length=255, verbose_name='Notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_emergencia', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Contacto de emergencia',
                'verbose_name_plural': 'Contactos de emergencia',
                'ordering': ['-es_principal', 'nombre'],
                'indexes': [models.Index(fields=['usuario', 'es_principal'], name='emergency_c_usuario_cd333f_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'telefono'), name='telefono_unico_por_usuario')],
            },
        ),
        migrations.CreateModel(
            name='EventoSOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activado', 'Activado'), ('resuelto', 'Resuelto'), ('falsa_alarma', 'Falsa Alarma')], db_index=True, default='activado', max_length=20, verbose_name='Estado')),
                ('ubicacion_latitud', models.DecimalField(blank=True, decimal_places=6, help_text='Latitud GPS del dispositivo al momento del SOS.', max_digits=9, null=True, verbose_name='Latitud')),
                ('ubicacion_longitud', models.DecimalField(blank=True, decimal_places=6, help_text='Longitud GPS del dispositivo al momento del SOS.', max_digits=9, null=True, verbose_name='Longitud')),
                ('notas', models.TextField(blank=True, default='', help_text='Observaciones del usuario al resolver o marcar como falsa alarma.', verbose_name='Notas')),
                ('dispositivo', models.CharField(blank=True, default='', help_text='User-Agent simplificado. Ej: "Chrome/Android", "Safari/iOS", "Firefox/Web".', max_length=100, verbose_name='Dispositivo')),
                ('direccion_aproximada', models.CharField(blank=True, default='', help_text='Dirección legible obtenida por geocodificación inversa (opcional).', max_length=255, verbose_name='Dirección aproximada')),
                ('duracion_segundos', models.PositiveIntegerField(blank=True, help_text='Tiempo en segundos entre activación y resolución. Calculado al resolver.', null=True, verbose_name='Duración del evento (seg)')),
                ('contactos_notificados', models.PositiveSmallIntegerField(default=0, help_text='Número de contactos de emergencia que el cliente notificó durante el evento.', verbose_name='Contactos notificados')),
                ('activado_en', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático del momento de activación.', verbose_name='Activado el')),
                ('resuelto_en', models.DateTimeField(blank=True, help_text='Cuándo fue resuelto o marcado como falsa alarma.', null=True, verbose_name='Resuelto el')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_sos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Evento SOS',
                'verbose_name_plural': 'Eventos SOS',
                'ordering': ['-activado_en'],
                'indexes': [models.Index(fields=['usuario', 'estado'], name='emergency_e_usuario_fe1cd8_idx'), models.Index(fields=['usuario', 'activado_en'], name='emergency_e_usuario_21f7ba_idx')],
            },
        ),
    ]
