# Generated by Django 6.0.5 on 2026-05-09 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoemergencia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_emergencia', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='eventosos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_sos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddConstraint(
            model_name='numeroservicioemergencia',
            constraint=models.UniqueConstraint(fields=('telefono', 'codigo_pais'), name='telefono_unico_por_pais'),
        ),
        migrations.AddIndex(
            model_name='contactoemergencia',
            index=models.Index(fields=['usuario', 'es_principal'], name='emergency_c_usuario_cd333f_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactoemergencia',
            constraint=models.UniqueConstraint(fields=('usuario', 'telefono'), name='telefono_unico_por_usuario'),
        ),
        migrations.AddIndex(
            model_name='eventosos',
            index=models.Index(fields=['usuario', 'estado'], name='emergency_e_usuario_fe1cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='eventosos',
            index=models.Index(fields=['usuario', 'activado_en'], name='emergency_e_usuario_21f7ba_idx'),
        ),
    ]
