# Generated by Django 6.0.5 on 2026-05-12 03:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoemergencia',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='contactoemergencia',
            name='email',
            field=models.EmailField(blank=True, help_text='Email del contacto para notificaciones opcionales.', max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='contactoemergencia',
            name='notas',
            field=models.CharField(blank=True, default='', help_text='Información adicional del contacto. Ej: "Disponible solo en horario laboral".', max_length=255, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='eventosos',
            name='contactos_notificados',
            field=models.PositiveSmallIntegerField(default=0, help_text='Número de contactos de emergencia que el cliente notificó durante el evento.', verbose_name='Contactos notificados'),
        ),
        migrations.AddField(
            model_name='eventosos',
            name='direccion_aproximada',
            field=models.CharField(blank=True, default='', help_text='Dirección legible obtenida por geocodificación inversa (opcional).', max_length=255, verbose_name='Dirección aproximada'),
        ),
        migrations.AddField(
            model_name='eventosos',
            name='dispositivo',
            field=models.CharField(blank=True, default='', help_text='User-Agent simplificado. Ej: "Chrome/Android", "Safari/iOS", "Firefox/Web".', max_length=100, verbose_name='Dispositivo'),
        ),
        migrations.AddField(
            model_name='eventosos',
            name='duracion_segundos',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo en segundos entre activación y resolución. Calculado al resolver.', null=True, verbose_name='Duración del evento (seg)'),
        ),
        migrations.AddField(
            model_name='numeroservicioemergencia',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='numeroservicioemergencia',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numeroservicioemergencia',
            name='horario_atencion',
            field=models.CharField(blank=True, default='24/7', help_text='Descripción del horario. Ej: "24/7", "Lun-Vie 08:00-18:00".', max_length=100, verbose_name='Horario de atención'),
        ),
        migrations.AddField(
            model_name='numeroservicioemergencia',
            name='icono',
            field=models.CharField(blank=True, default='', help_text='Nombre del ícono a mostrar en el frontend. Ej: "ambulance", "police", "fire".', max_length=50, verbose_name='Ícono'),
        ),
        migrations.AddField(
            model_name='numeroservicioemergencia',
            name='url_sitio_web',
            field=models.URLField(blank=True, help_text='URL del sitio oficial del servicio. Ej: https://www.pnp.gob.pe/', null=True, verbose_name='Sitio web'),
        ),
    ]
