# Generated by Django 6.0.5 on 2026-05-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='esta_verificado',
            field=models.BooleanField(default=False, help_text='True cuando el usuario ha confirmado su correo electrónico.', verbose_name='Cuenta verificada'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Utilizada para calcular la edad del usuario en reportes.', null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Imagen de avatar del usuario. Se almacena en /media/usuarios/fotos/', null=True, upload_to='usuarios/fotos/', verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no decir')], max_length=1, null=True, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pais',
            field=models.CharField(default='PE', help_text='Código ISO del país. Ej: PE, CO, MX. Filtra servicios de emergencia locales.', max_length=5, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono en formato internacional. Ej: +51999888777', max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['pais'], name='users_usuar_pais_0bfd99_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['esta_verificado'], name='users_usuar_esta_ve_4b8509_idx'),
        ),
    ]
