# Generated by Django 6.0.5 on 2026-05-12 03:30

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_enriquecer_modelos_usuario_emergency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(help_text='Direccion de correo unica por usuario. Ej: maria@gmail.com', max_length=255, unique=True, validators=[django.core.validators.EmailValidator(message='Formato de correo invalido. Ej: usuario@dominio.com')], verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='esta_verificado',
            field=models.BooleanField(default=False, help_text='True cuando el usuario confirma su correo electronico.', verbose_name='Cuenta verificada'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(help_text='Nombre(s) del usuario.', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Avatar del usuario. Ruta relativa en /media/usuarios/fotos/', null=True, upload_to='usuarios/fotos/', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no decir')], max_length=1, null=True, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(help_text='Apellido(s) del usuario.', max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pais',
            field=models.CharField(default='PE', help_text='Codigo ISO del pais. Ej: PE, CO, MX. Filtra servicios de emergencia locales.', max_length=5, verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, help_text='Numero de telefono en formato internacional. Ej: +51999888777', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Numero invalido. Usa formato internacional: +51999888777', regex='^\\+?\\d{7,15}$')], verbose_name='Telefono'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='users_usuar_email_af433f_idx'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('email__icontains', '@')), name='chk_email_contiene_arroba'),
        ),
    ]
