# Generated by Django 6.0.5 on 2026-05-12 21:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alinear_usuario_esquema_dba'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Registros de auditoria',
                'db_table': 'audit_log',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('CIUDADANO', 'Ciudadano'), ('SOCORRISTA', 'Socorrista'), ('COORDINADOR', 'Coordinador'), ('ADMIN', 'Admin')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.RESTRICT, to='users.rol')),
                ('pk', models.CompositePrimaryKey('user', 'role', blank=True, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, db_column='assigned_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol de usuario',
                'verbose_name_plural': 'Roles de usuario',
                'db_table': 'user_roles',
            },
        ),
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=users.models.generar_token_verificacion, max_length=255, unique=True)),
                ('token_type', models.CharField(choices=[('EMAIL_VERIFICATION', 'Verificacion de email'), ('PASSWORD_RESET', 'Restablecimiento de password'), ('PHONE_VERIFICATION', 'Verificacion de telefono')], max_length=50)),
                ('expires_at', models.DateTimeField(default=users.models.vencimiento_token_24h)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Token de verificacion',
                'verbose_name_plural': 'Tokens de verificacion',
                'db_table': 'verification_tokens',
            },
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', users.models.UsuarioManager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='usuario',
            name='chk_email_contiene_arroba',
        ),
        migrations.RemoveIndex(
            model_name='usuario',
            name='users_usuar_pais_0bfd99_idx',
        ),
        migrations.RemoveIndex(
            model_name='usuario',
            name='users_usuar_esta_ve_4b8509_idx',
        ),
        migrations.RenameIndex(
            model_name='usuario',
            new_name='idx_users_email',
            old_name='users_usuar_email_af433f_idx',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='date_joined',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='esta_verificado',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='telefono',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='actualizado_en',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Numero invalido. Usa formato internacional: +51999888777', regex='^\\+?\\d{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator(message='Formato de correo invalido. Ej: usuario@dominio.com')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, db_column='last_login_at', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(db_column='password_hash', max_length=255, verbose_name='password'),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='users',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', through='users.UserRole', through_fields=('user', 'role'), to='users.rol'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['is_active'], name='idx_users_is_active'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('email__regex', '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$')), name='chk_email_format'),
        ),
        migrations.AddField(
            model_name='verificationtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='foto_perfil',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='idx_audit_user_id'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='idx_audit_action'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_at'], name='idx_audit_created'),
        ),
        migrations.AddIndex(
            model_name='verificationtoken',
            index=models.Index(fields=['user'], name='idx_tokens_user_id'),
        ),
        migrations.AddIndex(
            model_name='verificationtoken',
            index=models.Index(condition=models.Q(('used', False)), fields=['token'], name='idx_tokens_token'),
        ),
        migrations.AddConstraint(
            model_name='verificationtoken',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__lt', models.F('created_at')), ('used', True), _negated=True), name='chk_token_not_expired_when_used'),
        ),
    ]
